server:
  port: 8087
  servlet:
    context-path: /review

spring:
  application:
    name: review-service

  datasource:
    url: ${DB_REVIEW_URL:jdbc:mysql://localhost:3307/techstore_review}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  services:
    identity: ${IDENTITY_SERVICE_URL:http://localhost:8080/identity}
    file: ${FILE_SERVICE_URL:http://localhost:8082/file}
    user: ${USER_SERVICE_URL:http://localhost:8081/user}
    product: ${PRODUCT_SERVICE_URL:http://localhost:8083/product}
    order: ${ORDER_SERVICE_URL:http://localhost:8086/order}
    moderation: ${MODERATION_SERVICE_URL:http://localhost:8089/moderation}