server:
  port: 8090
  servlet:
    context-path: /chatbot

spring:
  application:
    name: chatbot-service

  data:
    mongodb:
      uri: ${MONGO_CHATBOT_URI:mongodb://root:root@localhost:27018/techstore-chatbot?authSource=admin}
      auto-index-creation: true

app:
  services:
    product: ${PRODUCT_SERVICE_INTERNAL_URL:http://localhost:8083/product}
    warehouse: ${WAREHOUSE_SERVICE_INTERNAL_URL:http://localhost:8084/warehouse}
    order: ${ORDER_SERVICE_INTERNAL_URL:http://localhost:8086/order}
    identity: ${IDENTITY_SERVICE_INTERNAL_URL:http://localhost:8080/identity}
  session:
    secret: ${SESSION_KEY:b9fe0f207c53bf5eddca26bd363df8c4}

  gemini:
    api-keys:
      - key: ${GEMINI_API_KEY_1:your-api-key-1}
      - key: ${GEMINI_API_KEY_2:your-api-key-2}
      - key: ${GEMINI_API_KEY_3:your-api-key-3}
      - key: ${GEMINI_API_KEY_4:your-api-key-4}
    url: ${GEMINI_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent}
jwt:
    signerKey: ${JWT_SIGNER_KEY:u00HlI390ctLn7BGyr0F2HczWiIskDBeX9WFOk25MEGnFoEjKwFoZh6h7gcX3Z3pJ0BAr9AbbGXelLMviWbZoZ}
    valid-duration: ${JWT_VALID_DURATION:36000}
    refreshable-duration: ${JWT_REFRESH_DURATION:604800}

feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 15000

logging:
  level:
    com.techstore.chatbot: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG