server:
  port: 8083
  servlet:
    context-path: /product

spring:
  application:
    name: product-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  datasource:
    url: ${DB_PRODUCT_URL:jdbc:mysql://localhost:3307/techstore_product}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  services:
    identity: ${IDENTITY_SERVICE_URL:http://localhost:8080/identity}
    file: ${FILE_SERVICE_URL:http://localhost:8082/file}
    warehouse: ${WAREHOUSE_SERVICE_URL:http://localhost:8084/warehouse}