server:
  port: 8086
  servlet:
    context-path: /order

spring:
  application:
    name: order-service

  datasource:
    url: ${DB_ORDER_URL:jdbc:mysql://localhost:3307/techstore_order}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  services:
    user: ${USER_SERVICE_URL:http://localhost:8081/user}
    warehouse: ${WAREHOUSE_SERVICE_URL:http://localhost:8084/warehouse}
    product: ${PRODUCT_SERVICE_URL:http://localhost:8083/product}
    cart: ${CART_SERVICE_URL:http://localhost:8085/cart}

  ghn:
    base-url: ${GHN_BASE_URL:https://dev-online-gateway.ghn.vn/shiip/public-api}
    token: ${GHN_TOKEN}
    shipping:
      warehouse:
        province-id: ${GHN_PROVINCE_ID:220}
        district-id: ${GHN_DISTRICT_ID:1572}
        ward-code: ${GHN_WARD_CODE:550113}