server:
  port: 8085
  servlet:
    context-path: /cart

spring:
  application:
    name: cart-service

  datasource:
    url: ${DB_CART_URL:jdbc:mysql://localhost:3307/techstore_cart}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    hikari:
      initialization-fail-timeout: 60000

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

cart:
  ttl: 604800
  max-items-per-cart: 50

app:
  services:
    identity: ${IDENTITY_SERVICE_INTERNAL_URL:http://localhost:8080/identity}
    file: ${FILE_SERVICE_INTERNAL_URL:http://localhost:8082/file}
    product: ${PRODUCT_SERVICE_INTERNAL_URL:http://localhost:8083/product}
    order: ${ORDER_SERVICE_INTERNAL_URL:http://localhost:8086/order}